# Generated by Django 5.2.2 on 2025-06-05 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_chatprofile_chatproject'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatprofile',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chatproject',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
