# Generated by Django 5.2.2 on 2025-06-09 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_chatfeedback_like_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsession',
            name='response',
            field=models.TextField(blank=True, default=''),
        ),
    ]
